# Generated by Django 4.0.4 on 2022-05-06 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_shortcuts_shortcut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortcut',
            old_name='shortcut_usage',
            new_name='shortcut_accesses',
        ),
    ]
