# Generated by Django 4.0.4 on 2022-05-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_shortcut_usage_shortcut_shortcut_accesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_ip', models.TextField()),
                ('log_ua', models.TextField()),
                ('log_shortcut', models.TextField()),
                ('log_time', models.DateTimeField()),
            ],
        ),
    ]
