# Generated by Django 4.0.4 on 2022-05-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='shortcut_accesses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='shortcut_key',
            field=models.CharField(help_text='Key of the shortcut', max_length=20),
        ),
        migrations.AlterField(
            model_name='shortcut',
            name='shortcut_value',
            field=models.URLField(help_text='The target of the shortcut'),
        ),
    ]
